version: '3'
services:
  web:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:mysecretpassword@db:5432/foodtruck?schema=public'
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: foodtruck
    ports:
      - '5433:5432'
